package com.CodeBuilder.core.utils;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class Testhsqldb {

    public static void main(String[] args) throws Exception{

        Class.forName("org.hsqldb.jdbcDriver");

        String url = "jdbc:hsqldb:file:d:/hsqldb/test;shutdown=true";
        Connection c =DriverManager.getConnection(url, "root", "admin");
        Statement st = c.createStatement();

        /*String sql = "CREATE TABLE category (" +
                "  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY," +
                "  name varchar(255) DEFAULT NULL," +
                "  PRIMARY KEY (id)" +
                ")";
        st.execute(sql);

        String sql2 = "insert into category values (null,'category1')";
        st.execute(sql2);*/

        /*String sql3 = " drop table category";
        st.execute(sql3);
        String sql4 = " drop table setting";
        st.execute(sql4);*/

        ResultSet rs= st.executeQuery("select * from setting where is_default = '1' ");
        while(rs.next()){
            int id = rs.getInt("id");
            String name = rs.getString("author");
            System.out.println(id+"\t"+name);
        }
        st.close();
        c.close();

    }
}
